version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "cookiecutter"
    directory: "/"
    labels:
      - "dependency"
    versioning-strategy: "widen"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
